trigger:
- main

pool:
  name: Default

variables:
- group: My variable Group

steps:
- checkout: self

- powershell: |
    $ErrorActionPreference = "Stop"  
    $pat = "${env:pat}"
    az devops configure --defaults organization=$organization project=$project
    $env:AZURE_DEVOPS_EXT_PAT = $pat
    Write-Host "Publishing artifact..."
    az artifacts universal publish
    --organization https://dev.azure.com/tabpipelines/
    --feed test-01
    --scope project
    --name my-first-package
    --version 0.0.1
    --description "Welcome to Universal Packages"
    --path .
  displayName: 'Publish Artifact'

    
    

    
   
    

    
    

    


   
   


