trigger:
  branches:
    include:
      - 

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build, Test and Publish Artifact'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET Core sdk'
        inputs:
          packageType: 'sdk'
          version: '8.x'

      - script: dotnet restore
        displayName: 'Restore dependencies'

      - script: dotnet build --configuration Release
        displayName: 'Build application'

      - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
        displayName: 'Publish Application'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'  
      
      - script: | # logging step
          echo " ** Contents of $(Build.ArtifactStagingDirectory):"
          dir /b /s $(Build.ArtifactStagingDirectory)
        displayName: 'List files in Build.ArtifactStagingDirectory'
          
- stage: PromoteToAzureArtifacts  
  displayName: 'Promote Build Artifacts'
  dependsOn: Build  
  jobs:
  - job: Promote
    displayName: 'Promote Artifacts'
    steps:
      - script: | # logging step
          echo " ** Contents of $(Build.ArtifactStagingDirectory):"
          dir /b /s $(Build.ArtifactStagingDirectory)
        displayName: 'List files in Build.ArtifactStagingDirectory'
      - task: PublishBuildArtifacts@1  
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop-tabpipelines'  # Optional artifact name
